# Generated by Django 3.1 on 2020-08-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('customer_name', models.CharField(max_length=200)),
                ('checkin_date', models.DateTimeField(verbose_name='date checkin')),
                ('checkout_date', models.DateTimeField(verbose_name='date checkout')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0)),
                ('room_status', models.CharField(max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.room')),
            ],
        ),
        migrations.CreateModel(
            name='StayRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date stay')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.room')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.stay')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomavail.room'),
        ),
    ]
